name: GLORY Discord Bot

on:
  workflow_dispatch:
  push:
    branches:
      - "1"

jobs:
  run-bot:
    runs-on: ubuntu-latest

    steps:
      - name: Code ophalen
        uses: actions/checkout@v4
        with:
          ref: "1"

      - name: Python installeren
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Packages installeren
        run: pip install -r requirements.txt

      - name: Bot starten
        env:
          DISCORD_TOKEN: ${{ secrets.DISCORD_TOKEN }}
        run: python bot.py
